#!/bin/bash
export HASKPATH=$(pwd)/
(echo 'export HASKPATH='$(pwd)/) >> ~/.bashrc
#(nproc --all) > haskemd/haskemd/processors
PATH=$PATH:~/.local/bin
(echo 'PATH=$PATH:~/.local/bin') >> ~/.bashrc
BREW_CHECK=$(type brew > /dev/null)
if [ ! $BREW_CHECK ] && [ "$OSTYPE" == "darwin"* ] ; then
    echo 'downloading brew for Mac to install required packages...'
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi
APT_GET_CMD=$(which apt-get)
YUM_CMD=$(which yum)
PACMAN_CMD=$(which pacman)
BREW_CMD=$(which brew)
if [[ ! -z $APT_GET_CMD ]]; then
    sudo apt-get install -y libdevil-dev llvm imagemagick
elif [[ ! -z $BREW_CMD ]]; then
    brew install devil llvm imagemagick
elif [[ ! -z $YUM_CMD ]]; then
    yum install -y DevIL-devel imagemagick llvm
elif [[ ! -z $PACMAN_CMD ]]; then 
    pacman -S imagemagick devil llvm
else
    echo "Your package manager is not supported. Please install the DevIL image libray, llvm, and imagemagick."
fi
EMD_CMD=$(type EMD > /dev/null)
if ! $EMD_CMD ; then
    if ! type "stack" > /dev/null ; then
        wget -qO- https://get.haskellstack.org/ | sh
    fi
    stack setup && stack build && stack install
fi
cd haskemd/ && sudo python3 setup.py install && cd ../
mkdir data/
#echo 'binaries built, remove libraries? (y/n) (1.8G)'
#sudo rm -r ~/.stack/
#sudo rm -r .stack-work/
#echo 'test program now? (y/n)'
#python3 test.py
