#!/bin/bash
if [[ ! "$HASKPATh" == $(pwd) ]] ; then
    export HASKPATH=$(pwd)/
    (echo 'export HASKPATH='$(pwd)/) >> ~/.bashrc
fi
#(nproc --all) > haskemd/haskemd/processors
if [[ ! "PATH"=*":~/.local/bin"* ]] ; then
    echo 'adding ~/.local/bin to PATH'
    PATH=$PATH:~/.local/bin
    (echo 'PATH=$PATH:~/.local/bin') >> ~/.bashrc
fi
BREW_CHECK=$(type brew)
PORTS_CHECK=$(type ports)
if [ ! $BREW_CHECK > /dev/null ] && [ ! $PORTS_CHECK > /dev/null ] && [ "$OSTYPE" == "darwin"* ] ; then
    echo "Neither brew nor ports detected..."
    echo "Install brew (to automatically install dependencies)?"
    select yn in "Yes" "No"; do
        case $yn in
            Yes )     /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" ; break;;
            No ) exit;;
        esac
    done
fi
APT_GET_CMD=$(which apt-get)
YUM_CMD=$(which yum)
PACMAN_CMD=$(which pacman)
BREW_CMD=$(which brew)
PORTS_CMD=$(which port)
if [[ ! -z $APT_GET_CMD ]]; then
    echo "installing dependencies with apt-get...."
    (sudo apt-get install -y libdevil-dev llvm-3.8 imagemagick nvidia-cuda-dev) &> build.log
elif [[ ! -z $BREW_CMD ]]; then
    brew install devil llvm imagemagick
elif [[ ! -z $YUM_CMD ]]; then
    yum install -y DevIL-devel imagemagick llvm
elif [[ ! -z $PORTS_CMD ]]; then
    sudo port install ImageMagick libdevil llvm-3.8.1
elif [[ ! -z $PACMAN_CMD ]]; then 
    pacman -S imagemagick devil llvm cuda
    export PATH=$PATH:/opt/cuda/bin
    echo 'export PATH=$PATH:/opt/cuda/bin' >> ~/.bashrc
else
    echo "Your package manager is not supported. Please install the DevIL image libray, llvm, and imagemagick."
    echo "Your package manager is not supported. Please install the DevIL image libray, llvm, and imagemagick." >> builderrors.log
fi
if ! type "EMD" > /dev/null ; then
    if ! type "stack" > /dev/null ; then
        echo "Install stack (necessary to build)?"
        select yn in "Yes" "No"; do
            case $yn in
                Yes ) wget -qO- https://get.haskellstack.org/ | sh ; break;;
                No ) exit;;
            esac
        done
    fi
    echo "setting up stack..."
    (stack setup &>> build.log && stack build && stack install)
fi
cd haskemd/ && echo "Installing python package..." ; (sudo python3 setup.py install) >> ../build.log && cd ../
mkdir data/ &> /dev/null
if ! type "nvcc" > /dev/null ; then
    echo "" ; echo "Note that CUDA has not been installed! You will have to install it now"
    echo "Note that CUDA has not been installed! You will have to install it now" &>> build.log
fi
echo "Python built sucessfully."
#echo 'binaries built, remove libraries? (y/n) (1.8G)'
#sudo rm -r ~/.stack/
#sudo rm -r .stack-work/
#echo 'test program now? (y/n)'
#python3 test.py
